version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bandage-villaruel
    ports: 
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules